version: 2
jobs:
  build:
    working_directory: ~/server/
    docker:
      - image: circleci/node:12.9.0
      - image: postgres:11.5-alpine
        environment:
          POSTGRES_PASSWORD: testpassword
          POSTGRES_USER: testuser
          POSTGRES_DB: whatsapp
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Test
          command: yarn test
      - store_test_results:
          path: test-results
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn